apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: access-control-frontend-service
spec:
  ingressClassName: nginx
  rules:
  - host: flightfinder.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: access-control-frontend-service
            port:
              number: 3000