apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: danielneset/bachelor-gateway:prod-365caddd9bf90891c0d90e8f86458dc0f5ae3e47
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: REST_ROUTE_URI
            value: "http://restapi-service:8080"
          - name: PORT
            value: "8080"
          - name: DDL
            value: "update"
          - name: DB_HOST
            value: "mysql"
          - name: "DB_PORT"
            value: "3306"
          - name: "DB_NAME"
            value: "dev"
          - name: "DB_USERNAME"
            value: "root"
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
          - name: "JWT_KEY"
            valueFrom:
              secretKeyRef:
                name: api-jwt
                key: api-jwt-key