apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - phpmyadmin.flightfinder.space
    secretName: origin-ca-tls
  rules:
  - host: phpmyadmin.flightfinder.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phpmyadmin
            port:
              number: 80
